name: choseong_search
description: "Korean Choseong Search in Flutter"
version: 1.0.0
homepage: https://github.com/jhj0517/flutter_choseong_search

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
